[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/forge-std/src/interfaces/AggregatorV3Interface.sol","@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

[profile.dependencies]
"solidity-stringutils" = ">=0.2.11"

[invariant]
runs = 100
depth = 10
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config